services:
  - type: web
    name: stock-web
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stock-db
          property: connectionString

databases:
  - name: stock-db